name: CI
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1

    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install Dependencies
      run: npm install

    - name: Check just-install.json
      run: npm test

    - name: Install just-install from stable MSI installer
      run: msiexec.exe /q /i https://just-install.github.io/stable/just-install.msi

    - name: Audit registry
      run: just-install -r just-install-v4.json audit

    - name: Install all
      run: just-install -r just-install-v4.json 1password 7zip adoptopenjdk-13-jdk adoptopenjdk-13-jre adoptopenjdk-14-jdk adoptopenjdk-14-jre aescrypt-cli aescrypt-gui amazon-corretto-11 amazon-corretto-8 anaconda android-studio-ide antimicro anydesk arduino atom audacity autohotkey autoruns aws-cli axcrypt azcopy azure-cli battlenet bcc bcuninstaller bitpay bitwarden bleachbit blender bootnext brackets brave calibre ccleaner cdburnerxp chrome-remote-desktop-host citrix-receiver classic-shell clementine-player cmake codeblocks codeblocks-mingw colemak conan conemu cpu-z cryptomator crystaldisk-info crystaldisk-mark cyberduck cygwin dbeaver deluge dependency-walker directx-june2010 discord displaycal ditto dotnet doublecmd dropbox duck dynalist eac eclipse-committers eclipse-cpp eclipse-java eclipse-jee eclipse-php eig em-client emacs enpass epic-games-launcher erlang etcher everything-search exeproxy fences ffmpeg filezilla filezilla-server firefox firefox-beta firefox-developer-edition firefox-esr flash-player flash-player-ie flux foxitreader freecad freeplane geforce-experience gimp git git-credential-manager-for-windows git-lfs gitextensions github gitkraken go gog-galaxy google-chrome google-chrome-beta google-chrome-dev google-drive gow gpg4win greenshot gvim handbrake hashcheck heidisql hexchat hugo imageglass inkscape innosetup irfanview itch jetbrains-toolbox jom keepass keepass-keepasshttp keepassxc keeweb keybase kicad kodi krita libreoffice lightshot lockhunter mailspring mailstore-home malwarebytes marktext mednafen mercurial microsoft-security-essentials mono moonlight-qt mountainduck mp3tag mpc-hc mremoteng mumble mysql-workbench naps2 nettime nextcloud nircmd node node-lts nordvpn notepad++ notepad2-mod npackd npackdcl nxlog obs-studio octave onlyoffice-desktopeditors open-hardware-monitor openssh openvpn-win10 openvpn-win7 opera origin paint.net parsec pdf24 perl photofiltre php physx pia plex-media-server postman potplayer powershell-core processhacker procmon putty pycharm-community python2 python2-vc python3 python3-minimal qbittorrent qtox rambox-community rapidee rclone rclone-browser resilio-sync resource-hacker retroarch ruby rufus sdm seafile-client sharex sharpkeys shotcut signal simplenote slack smplayer sourcetree spice-guest-tools sshfs-win steam sublime-text sublime-text-3 sublime-text-dev subversion sumatrapdf syncthing sysinternals teamspeak teamviewer telegram thunderbird tightvnc tor-browser torguard tortoisegit tortoisesvn transmission uplay upx vagrant vcredist-2005 vcredist-2008 vcredist-2010 vcredist-2012 vcredist-2013 vcredist-2015 vcredist-2017 vcredist-2019 vcvrack veracrypt virtualbox viscosity visual-studio-code visual-studio-community-2017 visual-studio-community-2019 visual-studio-enterprise-2017 visual-studio-enterprise-2019 visual-studio-professional-2017 visual-studio-professional-2019 vivaldi vlc voicemeeter voicemeeter-banana webtorrent whatsapp windirstat windows-usb-dvd-tool winfsp winrar winscp wireshark wix wixedit workflowy wox yarn yatqa youtube-dl
